<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>2.2.2</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FikaSync\FikaSync.csproj" />
      <ProjectReference Include="..\Plugin\Plugin.csproj" />
      <ProjectReference Include="..\Prepatcher\Prepatch.csproj" />
      <ProjectReference Include="..\Server\Server.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TarkovDir Condition=" '$(TarkovDir)' == '' ">$(SolutionDir)..\..\</TarkovDir>
    </PropertyGroup>

    <!-- Gets the commit hash from git -->
    <Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
        <Exec
                Command="git describe --long --always --dirty --exclude=* --abbrev=8"
                ConsoleToMSBuild="True"
                IgnoreExitCode="False"
        >
            <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput"/>
        </Exec>
    </Target>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <Plugin     Include="$(TarkovDir)BepInEx\plugins\SkillsExtended\**\*.*" />
            <SyncPlugin Include="$(TarkovDir)BepInEx\plugins\SkillsExtended\SkillsExtendedFika.dll" />
            <PrePatch   Include="$(TarkovDir)BepInEx\patchers\SkillsExtended_PrePatch.dll" />
            <Server     Include="$(TarkovDir)SPT\user\mods\SkillsExtended\**\*.*"/>
        </ItemGroup>
        
        <!-- Clean the release directory -->
        <RemoveDir Directories="$(SolutionDir)release" />

        <!-- Copy the plugin -->
        <Copy
                SourceFiles="@(Plugin)"
                DestinationFolder="$(SolutionDir)release\SkillsExtended\BepInEx\plugins\SkillsExtended\%(RecursiveDir)"
        />
        
        <!-- Delete the Fika sync plugin so it doesn't get bundled in the main release zip -->
        <Delete Files="$(SolutionDir)release\SkillsExtended\BepInEx\plugins\SkillsExtended\SkillsExtendedFika.dll"/>

        <!-- Copy the prepatch -->
        <Copy
                SourceFiles="@(PrePatch);"
                DestinationFolder="$(SolutionDir)release\SkillsExtended\BepInEx\patchers\"
        />

        <!-- Copy the server mod -->
        <Copy
                SourceFiles="@(Server);"
                DestinationFolder="$(SolutionDir)release\SkillsExtended\SPT\user\mods\SkillsExtended\%(RecursiveDir)"
        />

        <!-- Zip the mod into a release format -->
        <ZipDirectory
                SourceDirectory="$(SolutionDir)release\SkillsExtended\"
                DestinationFile="$(SolutionDir)release\SkillsExtended-$(Version)-$(Configuration)-$(SourceRevisionId).zip"
        />

        <!-- Copy the sync plugin -->
        <Copy
                SourceFiles="@(SyncPlugin)"
                DestinationFolder="$(SolutionDir)release\SkillsExtendedFika\BepInEx\plugins\SkillsExtended\%(RecursiveDir)"
        />

        <!-- Zip into a release format -->
        <ZipDirectory
                SourceDirectory="$(SolutionDir)release\SkillsExtendedFika\"
                DestinationFile="$(SolutionDir)release\SkillsExtendedFika-$(Configuration)-$(SourceRevisionId).zip"
        />
        
    </Target>
    
</Project>
