using System.Collections.Generic;

namespace SkillsExtended.Config;

// Display defaults from the installed EFT skill rules and SPT 4.1 globals.
// Server-backed defaults are replaced by the loaded globals, before our overrides.
internal static class NativeSkillDefaults
{
    internal static readonly IReadOnlyDictionary<string, float> Values = new Dictionary<string, float>
    {
        ["Buff.36.PerLevel"] = 2f,
        ["Buff.38.PerLevel"] = 2f,
        ["Buff.39.PerLevel"] = 2f,
        ["Buff.44.PerLevel"] = 2f,
        ["Buff.45.PerLevel"] = 2f,
        ["Buff.46.Elite"] = 50f,
        ["Buff.48.PerLevel"] = 60f,
        ["Buff.49.PerLevel"] = 60f,
        ["Buff.50.PerLevel"] = 80f,
        ["Buff.65.PerLevel"] = 0.4f,
        ["Buff.66.PerLevel"] = 0.3f,
        ["Buff.67.PerLevel"] = 0.8f,
        ["Buff.68.Max"] = 50f,
        ["Buff.71.Max"] = 50f,
        ["Buff.77.PerLevel"] = 1.2f,
        ["Buff.84.PerLevel"] = 0.2f,
        ["Buff.88.PerLevel"] = 0.5f,
        ["Buff.89.PerLevel"] = 1f,
        ["Buff.93.Elite"] = 60f,
        ["Buff.93.PerLevel"] = 0.6f,
        ["Buff.95.PerLevel"] = 1f,
        ["Buff.97.Elite"] = 100f,
        ["Buff.97.PerLevel"] = 1f,
        ["Buff.98.Elite"] = 40f,
        ["Buff.98.Max"] = 20f,
        ["Charisma.BonusSettings.EliteBonusSettings.FenceStandingLossDiscount"] = 50.0f,
        ["Charisma.BonusSettings.EliteBonusSettings.RepeatableQuestExtraCount"] = 1f,
        ["Charisma.BonusSettings.EliteBonusSettings.ScavCaseDiscount"] = 10.0f,
        ["Charisma.BonusSettings.LevelBonusSettings.HealthRestoreDiscount"] = 0.1f,
        ["Charisma.BonusSettings.LevelBonusSettings.HealthRestoreTraderDiscount"] = 0.1f,
        ["Charisma.BonusSettings.LevelBonusSettings.InsuranceDiscount"] = 0.1f,
        ["Charisma.BonusSettings.LevelBonusSettings.InsuranceTraderDiscount"] = 0.1f,
        ["Charisma.BonusSettings.LevelBonusSettings.PaidExitDiscount"] = 0.1f,
        ["Charisma.BonusSettings.LevelBonusSettings.RepeatableQuestChangeDiscount"] = 0.1f,
        ["Crafting.CraftTimeReductionPerLevel"] = 0.75f,
        ["Crafting.EliteExtraProductions"] = 1f,
        ["Crafting.ProductionTimeReductionPerLevel"] = 0.75f,
        ["HeavyVests.BluntThroughputDamageHVestsReducePerLevel"] = 0.4f,
        ["HeavyVests.MoveSpeedPenaltyReductionHVestsReducePerLevel"] = 0.5f,
        ["HeavyVests.WearAmountRepairHVestsReducePerLevel"] = 1.0f,
        ["HeavyVests.WearChanceRepairHVestsReduceEliteLevel"] = 50.0f,
        ["HideoutManagement.CircleOfCultistsBonusPercent"] = 1.0f,
        ["HideoutManagement.ConsumptionReductionPerLevel"] = 0.5f,
        ["HideoutManagement.SkillBoostPercent"] = 1f,
        ["Intellect.RepairPointsCostReduction"] = 0.4f,
        ["Intellect.WearAmountReducePerLevel"] = 0.4f,
        ["Intellect.WearChanceReduceEliteLevel"] = 50.0f,
        ["LightVests.MeleeDamageLVestsReducePerLevel"] = 0.6f,
        ["LightVests.MoveSpeedPenaltyReductionLVestsReducePerLevel"] = 0.6f,
        ["LightVests.WearAmountRepairLVestsReducePerLevel"] = 0.8f,
        ["LightVests.WearChanceRepairLVestsReduceEliteLevel"] = 50.0f,
        ["RecoilControl.RecoilBonusPerLevel"] = 0.3f,
        ["TroubleShooting.EliteAmmoChanceReduceMult"] = 0.3f,
        ["TroubleShooting.EliteDurabilityChanceReduceMult"] = 0.3f,
        ["TroubleShooting.EliteMagChanceReduceMult"] = 0.3f,
        ["TroubleShooting.MalfRepairSpeedBonusPerLevel"] = 0.5f,
        ["WeaponTreatment.DurLossReducePerLevel"] = 0.5f,
        ["WeaponTreatment.WearAmountRepairGunsReducePerLevel"] = 1.0f,
        ["WeaponTreatment.WearChanceRepairGunsReduceEliteLevel"] = 50.0f,
    };
}
