<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup><EmbeddedResource Include="../Server/SkillsExtended.Server/Resources/Locales/en.json" LogicalName="SkillsExtended.Locales.en.json" /></ItemGroup>
</Project>
